(install
 (section share)
 (files
  (app.c as libC/app.c)
  (app.h as libC/app.h)
  (blame.c as libC/blame.c)
  (blame.h as libC/blame.h)
  (capp.c as libC/capp.c)
  (capp.h as libC/capp.h)
  (crc.c as libC/crc.c)
  (crc.h as libC/crc.h)
  (fun.h as libC/fun.h)
  (lst.c as libC/lst.c)
  (lst.h as libC/lst.h)
  (ref.h as libC/ref.h)
  (ref.c as libC/ref.c)
  (runtime.h as libC/runtime.h)
  (stdlib.c as libC/stdlib.c)
  (stdlib.h as libC/stdlib.h)
  (tpl.c as libC/tpl.c)
  (tpl.h as libC/tpl.h)
  (ty.c as libC/ty.c)
  (ty.h as libC/ty.h)
  (types.h as libC/types.h)))
