(install
 (section share)
 (files
  (app.c as libC/app.c)
  (app.h as libC/app.h)
  (blame.c as libC/blame.c)
  (blame.h as libC/blame.h)
  (capp.c as libC/capp.c)
  (capp.h as libC/capp.h)
  (crc.c as libC/crc.c)
  (crc.h as libC/crc.h)
  (dbl.h as libC/dbl.h)
  (fun.h as libC/fun.h)
  (lst.c as libC/lst.c)
  (lst.h as libC/lst.h)
  (ref.h as libC/ref.h)
  (ref.c as libC/ref.c)
  (arr.h as libC/arr.h)
  (arr.c as libC/arr.c)
  (runtime.h as libC/runtime.h)
  (stdlib_macros.h as libC/stdlib_macros.h)
  (stdlib_io.c as libC/stdlib_io.c)
  (stdlib_io.h as libC/stdlib_io.h)
  (stdlib_basic.c as libC/stdlib_basic.c)
  (stdlib_basic.h as libC/stdlib_basic.h)
  (stdlib_math.c as libC/stdlib_math.c)
  (stdlib_math.h as libC/stdlib_math.h)
  (stdlib_random.c as libC/stdlib_random.c)
  (stdlib_random.h as libC/stdlib_random.h)
  (stdlib_list.c as libC/stdlib_list.c)
  (stdlib_list.h as libC/stdlib_list.h)
  (stdlib_array.c as libC/stdlib_array.c)
  (stdlib_array.h as libC/stdlib_array.h)
  (stdlib.h as libC/stdlib.h)
  (tpl.c as libC/tpl.c)
  (tpl.h as libC/tpl.h)
  (ty.c as libC/ty.c)
  (ty.h as libC/ty.h)
  (types.h as libC/types.h)))
