#ifndef STDLIB_LIST_H
#define STDLIB_LIST_H

#include "types.h"
#include "stdlib_macros.h"

#define STDLIB_LIST_UNARY_LIST(X) \
  X(list_length)
#define STDLIB_LIST_BINARY_LIST(X) \
  X(list_map) X(list_init) X(list_mapi) X(list_iteri)
#define STDLIB_LIST_TRINARY_LIST(X) \
  X(list_fold_left)

STDLIB_LIST_UNARY_LIST(STDLIB_DECL_UNARY)
STDLIB_LIST_BINARY_LIST(STDLIB_DECL_BINARY)
STDLIB_LIST_TRINARY_LIST(STDLIB_DECL_TRINARY)

STDLIB_LIST_UNARY_LIST(STDLIB_DECL_EXTERN)
STDLIB_LIST_BINARY_LIST(STDLIB_DECL_EXTERN)
STDLIB_LIST_TRINARY_LIST(STDLIB_DECL_EXTERN)

#endif
