#ifndef STDLIB_ARRAY_H
#define STDLIB_ARRAY_H

#include "types.h"
#include "stdlib_macros.h"

#define STDLIB_ARRAY_UNARY_LIST(X) \
  X(array_to_list)
#define STDLIB_ARRAY_BINARY_LIST(X) \
  X(array_iteri)

STDLIB_ARRAY_UNARY_LIST(STDLIB_DECL_UNARY)
STDLIB_ARRAY_BINARY_LIST(STDLIB_DECL_BINARY)

STDLIB_ARRAY_UNARY_LIST(STDLIB_DECL_EXTERN)
STDLIB_ARRAY_BINARY_LIST(STDLIB_DECL_EXTERN)

#endif
