lS1dti ack.ml -c
lS1dti adder.ml -c
lS1dti adder2.ml -c
lS1dti cast_coercion_difference.ml -c
lS1dti cast-abort.ml -c
lS1dti cls-bug.ml -c
lS1dti cls-rec.ml -c
lS1dti even-odd.ml -c
lS1dti example1_fail.ml -c
lS1dti example1_success.ml -c
lS1dti example2.ml -c
lS1dti example3.ml -c
lS1dti fib.ml -c
lS1dti funcomp.ml -c
lS1dti gcd.ml -c
lS1dti join-reg.ml -c
lS1dti join-reg2.ml -c
lS1dti join-stack.ml -c
lS1dti join-stack2.ml -c
lS1dti join-stack3.ml -c
lS1dti many_coerce.ml -c
lS1dti non-tail-if.ml -c
lS1dti print.ml -c
lS1dti repeat_f_dyn.ml -c
lS1dti repeat_x_dyn.ml -c
lS1dti repeat.ml -c
lS1dti shuffle.ml -c
lS1dti sum-tail.ml -c
lS1dti sum.ml -c